# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NECopyRightMedia-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NECopyRightMedia-Example

  #RTC集成
  pod 'NERtcSDK','4.2.151'
  pod 'YYModel'
  pod 'YXAlog_iOS'
  pod 'NECopyrightedMedia','~> 1.1.0'
  pod 'Masonry', '~> 1.1.0'
  target 'NECopyRightMedia-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NECopyRightMedia-ExampleUITests' do
    # Pods for testing
  end

end
